# Generated by Django 4.2.4 on 2023-08-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'DOCTOR'), ('3', 'PATIENT'), ('4', 'COMPANY')], max_length=50, unique=True),
        ),
    ]
