# Generated by Django 4.2.1 on 2023-08-02 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_mygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='MyGroup',
        ),
    ]
