# Generated by Django 4.2.2 on 2023-06-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_bacteriologistuser_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacteriologistuser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='brigadeuser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctoruser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otheruser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receptionistuser',
            name='last_login_refferer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
