# Generated by Django 4.2.2 on 2023-06-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_bacteriologistuser_last_login_refferer_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteriologistuser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='bacteriologistuser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='brigadeuser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='brigadeuser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='otheruser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='otheruser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='last_login_refferer_url',
        ),
        migrations.RemoveField(
            model_name='receptionistuser',
            name='last_login_device',
        ),
        migrations.RemoveField(
            model_name='receptionistuser',
            name='last_login_refferer_url',
        ),
    ]
