# Generated by Django 4.2.1 on 2023-08-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_company_remove_role_group_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
