# Generated by Django 4.2.1 on 2023-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_rol_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='company_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
