# Generated by Django 4.2.2 on 2023-06-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bacteriologistuser_login_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteriologistuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='brigadeuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='otheruser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patientuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='receptionistuser',
            name='role',
        ),
        migrations.AddField(
            model_name='userbase',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.role'),
        ),
    ]
