# Generated by Django 4.2.1 on 2023-08-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_patient_company_section_patient_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='company_section',
            new_name='section',
        ),
    ]
