# Generated by Django 4.2.2 on 2023-08-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0002_remove_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecordbodypart',
            name='body_part',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.bodypart'),
        ),
    ]
