# Generated by Django 4.2.2 on 2023-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0003_alter_medicalrecordbodypart_body_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordbodypart',
            name='body_part',
        ),
        migrations.AddField(
            model_name='medicalrecordbodypart',
            name='body_part',
            field=models.ManyToManyField(blank=True, to='medical_record.bodypart'),
        ),
    ]
