# Generated by Django 4.2.2 on 2023-08-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0004_remove_medicalrecordbodypart_body_part_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecordbodypart',
            name='body_part',
        ),
        migrations.RemoveField(
            model_name='medicalrecordbodypart',
            name='medical_record',
        ),
        migrations.AddField(
            model_name='medicalrecordbodypart',
            name='body_part',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.bodypart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecordbodypart',
            name='medical_record',
            field=models.ManyToManyField(to='medical_record.medicalrecord'),
        ),
    ]
