# Generated by Django 4.2.2 on 2023-08-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0007_remove_medicalrecord_company_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='medicalconcept',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='ocuppationalinfo',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='physicalexam',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='visualsystem',
            name='medical_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalrecord'),
        ),
    ]
