# Generated by Django 4.2.1 on 2023-08-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_emphasis_emphasis'),
        ('medical_record', '0008_alter_diagnostic_medical_record_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalconcept',
            old_name='observations',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='medicalconcept',
            name='kind',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment'),
        ),
        migrations.AlterField(
            model_name='medicalrecordrecommendation',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Postponed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_postponed_date', models.DateField(blank=True, null=True)),
                ('requirements_to_lift_postponed', models.TextField(blank=True, null=True)),
                ('medical_concept', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalconcept')),
            ],
        ),
        migrations.CreateModel(
            name='HasRestrictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_time', models.TextField(blank=True, null=True)),
                ('restriction_detail', models.TextField(blank=True, null=True)),
                ('medical_concept', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalconcept')),
            ],
        ),
        migrations.CreateModel(
            name='EmphasisInMedicalConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('medical_concept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medical_record.medicalconcept')),
            ],
        ),
    ]
