# Generated by Django 4.2.1 on 2023-08-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultExams',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='city',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examprice',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
