# Generated by Django 4.2.4 on 2023-09-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
