# Generated by Django 4.2.2 on 2023-06-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='price',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='exampackage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exampackage',
            name='package',
        ),
        migrations.AddField(
            model_name='exampackage',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='exams_package',
            field=models.ManyToManyField(blank=True, related_name='exams_package', to='exam.package'),
        ),
    ]
