# Generated by Django 4.2.4 on 2023-08-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='examprice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examprice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='updated_at',
        ),
    ]
