# Generated by Django 4.2.2 on 2023-06-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_price_remove_exam_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='exams_package',
            field=models.ManyToManyField(blank=True, related_name='exams_package', to='exam.exampackage'),
        ),
    ]
