# Generated by Django 4.2.2 on 2023-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_tariff_exams_package'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamPackage',
            new_name='ExamPrice',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='exams_package',
        ),
        migrations.AddField(
            model_name='tariff',
            name='exams_prices',
            field=models.ManyToManyField(blank=True, related_name='exams_prices', to='exam.examprice'),
        ),
    ]
