# Generated by Django 4.2.1 on 2023-08-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='AKA',
            new_name='short_name',
        ),
    ]
