# Generated by Django 4.2.1 on 2023-08-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_defaultexams_remove_tariff_city_and_more'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncompany',
            name='tariff',
            field=models.ManyToManyField(blank=True, to='exam.tariff'),
        ),
        migrations.AlterField(
            model_name='missioncompany',
            name='active',
            field=models.BooleanField(),
        ),
    ]
