# Generated by Django 4.2.2 on 2023-06-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='exams',
        ),
    ]
