# Generated by Django 4.2.4 on 2023-08-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='emphasis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emphasis',
            name='updated_at',
        ),
    ]
