# Generated by Django 4.2.1 on 2023-08-12 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='emphasis',
        ),
        migrations.CreateModel(
            name='Emphasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
            ],
        ),
    ]
