# Generated by Django 4.2.2 on 2023-06-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_city_tariff_city'),
        ('appointment', '0002_remove_appointment_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
