# Generated by Django 4.2.1 on 2023-06-18 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_companyinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='limit_amount',
            new_name='balance',
        ),
    ]
