# Generated by Django 4.2.1 on 2023-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_appointment_emphasis_emphasis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='company_section',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='evaluation_type',
            field=models.CharField(max_length=255),
        ),
    ]
