# Generated by Django 4.2.4 on 2023-09-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('appointment', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='exam_list', to='exam.exam'),
        ),
    ]
