# Generated by Django 4.2.4 on 2023-09-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('appointment', '0003_appointment_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='exam_price', to='exam.examprice'),
        ),
    ]
