# Generated by Django 4.2.1 on 2023-06-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_limit_amount_companyinfo_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missioncompany',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='missioncompany',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
