# Generated by Django 4.2.2 on 2023-06-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_city_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='economy_activity',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='tariff',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='missioncompany',
            name='company',
        ),
    ]
