# Generated by Django 4.2.2 on 2023-06-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('appointment', '0004_remove_companyinfo_economy_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.companyinfo'),
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.DeleteModel(
            name='EconomyActivity',
        ),
        migrations.DeleteModel(
            name='MissionCompany',
        ),
    ]
