# Generated by Django 4.2.1 on 2023-06-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_missioncompany_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamsPackage',
            new_name='ExamPackage',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='appointment.tariff')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='exams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.exam'),
        ),
        migrations.DeleteModel(
            name='Exams',
        ),
    ]
