# Generated by Django 4.2.1 on 2023-08-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
    ]
