# Generated by Django 4.2.1 on 2023-06-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_exam_created_at_alter_exam_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
