# Generated by Django 4.2.1 on 2023-06-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_tariff_created_at_alter_tariff_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='tariff',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='tariff',
            field=models.ManyToManyField(blank=True, to='appointment.tariff'),
        ),
    ]
